### PR TITLE
Adds build and deploy GitHub action

### PR DESCRIPTION
**Pull request by jatin69**
1. Added a github action that'll publish the site to `gh_pages`, thus making it available at https://ducs.in/csdu-jekyll-website/

2. A minor fix in `_config.yml`

### CODE REVIEW

**Comment by jatin69** [comment]
Don't mind the number of commits, i was doing it in browser. You can probably squash and merge.

**Comment by yuvrajsab** [comment]
`gh-pages` branch should only contain contents of `_site` directory. i dont know why it has all the unnecessary files, and if you visit https://ducs.in/csdu-jekyll-website/src/ you can see build files.

**Review by yuvrajsab — COMMENTED** [review]
please look into the issue that i've commented

**Comment by rumansaleem** [comment]
This is happening, probably due to the `url` option in the config, `url` should only contain the host name, and the baseurl can be configured with `baseurl` option in the config file.

**Comment by yuvrajsab** [comment]
or we can use `jekyll action` which seems to work well with github. See this official deployment guide https://jekyllrb.com/docs/continuous-integration/github-actions/

**Comment by jatin69** [comment]
> or we can use `jekyll action` which seems to work well with github. See this official deployment guide https://jekyllrb.com/docs/continuous-integration/github-actions/

Jekyll classically do not use minifiers and purgers as can be seen in a sample from the action repo you mentioned - [sample site](https://github.com/helaili/jekyll-action/tree/master/sample_site). But we make use of them using npm. So no, we can't use this github action as it is. We need to tell npm to do our purges and everything.

> gh-pages branch should only contain contents of _site directory.

Yes my intention was to do that.

> i dont know why it has all the unnecessary files, and if you visit https://ducs.in/csdu-jekyll-website/src/ you can see build files.

You are right here. This is probably because of the github action i used in the workflow. It uses `git add --all` in its workflow, probably that's why everything is being pushed. We can easily correct by making changes in our workflow. I'll spend some time tonight to see what the best way to do that would be. 

> This is happening, probably due to the `url` option in the config, `url` should only contain the host name, and the baseurl can be configured with `baseurl` option in the config file.

@rumansaleem This is happening because gh-pages has that folder as @yuvrajsab pointed out. I doubt baseurl has anything to do here. Jekyll's work was over.

**Comment by jatin69** [comment]
@yuvrajsab Can you please build it locally and confirm that in local build these extra files are not generated inside `_site`. I think the action is doing its job fine here. But our `_config.yml` is not able to detect the source folder.

> This is happening, probably due to the `url` option in the config, `url` should only contain the host name, and the baseurl can be configured with `baseurl` option in the config file.

Even this is not out of scope for this investigation.

**Comment by rumansaleem** [comment]
I was trying to build locally, to investigate the same, but I couldn't get the `bundler` install `jekyll`. 😅 Maybe I am missing some ruby headers/extensions etc, could be a linux distro specific issue there.

**Review by yuvrajsab — COMMENTED** [review]
on my system, `_site` has only four item `css`, `jekyll`, `404.html`, `index.html` which is expected. im not getting any other irrelevant files.

**Comment by jatin69** [comment]
@rumansaleem Install ruby. Then use
```shell
gem install bundler
bundle install
npm install
npm run build
```

**Comment by rumansaleem** [comment]
I have ruby installed already v2.7.1. At `bundler install` step it shows up some error stating something like developer tools missing, I also installed `base-devel` from pacman, as given in jekyll's docs.

**Comment by jatin69** [comment]
@yuvrajsab @rumansaleem I've made the necessary changes.

The bug happened because -
- Initially the i used `.` instead of `_site` to deploy
- The action uses `amend` and `force push` so those files never got deleted.

What i did - 
- Manually purged them to correct the files introduced by `.`
- The action now works as intended.

**Review by rumansaleem — COMMENTED** [review]
Do we really need to build for development branch? It's okay if its `development` branch is deployed on some other URL. Otherwise, I think only master is enough

**Comment by jatin69** [comment]
@rumansaleem other URL support can be achieved with Now. 
Github pages won't be able to do that. 

And it's upto you guys, @yuvrajsab and @rumansaleem and decide and let me know if i should remove the development branch.

**Pull request merged**
